# Generated by Django 4.0.4 on 2022-06-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontend', '0002_delete_ratedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateBDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
