# Generated by Django 4.0.4 on 2022-06-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratebdd',
            name='movie_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratebdd',
            name='ratings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
